### ISSUE TITLE
Suggestion: Have excavator use materials in creative mode 

### ISSUE THREAD

**Issue by hb33green** [DancZer/Excavator#3]
I really like this mod because it is a lot less powerful than a lot of other excavation mods out there! Feels very close to vanilla! The only problem I have with it is that it doesn't seem to utilize the rails and torches that I place in it while it's mining. If I go in behind it I can pick up all that rail it placed down. This is basically item duping for rails and torches :/
I would love for it to be given 32 rails and therefore only move 32 blocks before running out... I'd have to spend the resources but not the time!

**Comment by DancZer** [comment]
Hi! I'm glad that you like it and gives me a feedback. I don't exactly understand what you suggesting. 
A: You can pick up the rail right after the miner placed id and this basically duplicate the rail?
B: Or you can't put rails in the miner while it is mining?

I'm open to improve and fix the issues, so I hope we can clarify your suggestion. Create a small video by demonstrating what you do,how you use it. That could help the discussion IMO.

**Comment by hb33green** [comment]
I am suggesting exactly what you're talking about in option A. I have provided a short clip of it here:
[https://imgur.com/a/6C7iGAc](url)

**Comment by DancZer** [comment]
So you play it in creative mode. This is by design. It does not consume rail and torch in creative mode. Because in creative mode it is basically free, so it makes no sense.

But I get your point. In creative mode the excavator moves to the infinite, and you would like to control the distance of excavation by the rail count.

I will make it consume the rail in creative mode, probably noone wants an infinite running excavator. I try to release it this week. Thank you for your feedback.

**Comment by DancZer** [comment]
Sorry for the delay. 

You can download the new version which would consume the Rail and Torches, no matter what mod you are in.
Release version is 1.9.0

https://www.curseforge.com/minecraft/mc-mods/excavator/files
